azicard/azicard/urls.py
from os import name
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),

]

if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [
            path("__debug__/", include(debug_toolbar.urls))
        ] + urlpatterns
        
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
                          

azicard/cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

azicard/coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

azicard/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('admin/order/<int:order_id>/', views.admin_order_detail,  name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf,  name='admin_order_pdf'),
]

azicard/shop/urls.py
from os import name
from django.urls import path
from .views import home_view , product_detail

app_name = 'shop'

urlpatterns = [
    path('', home_view, name='home'),
    path('product/<slug>/', product_detail, name='product'),

]

azicard/cart/models.py
from django.db import models

# Create your models here.

azicard/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

azicard/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from shop.models import Product

from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm

from .cart import Cart


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={
            'quantity': item['quantity'],
            'override': True})
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form})


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

azicard/templates/cart/detail.html
{% extends "shop/base.html" %} 
{% block title %} Shopping Cart {% endblock %}
{% load crispy_forms_tags %}

{% block content %}



  <div class="container wow fadeIn">
    <!-- Heading -->
    <!--    <h2 class="my-5 h2 text-center">Checkout form</h2>-->

    <!--Grid row-->
    <div class="row mt-5">
      <!--Grid column-->
      <div class="col-md-8 mb-4">
        <!--Card-->
        <div class="card">
          <!--Card content-->
          <div class="card-body ">

            <h2 class="h2" >Shopping Cart</h2>
              {% with total_items=cart|length %}
                {% if total_items > 0 %}
                    <h5 class="text-muted"> Currently you have  {{ total_items }} item(s) in your cart </h5>
                    <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Image</th>
                          <th>Product</th>
                          <th>Quantity</th>
                          <th>Remove</th>
                          <th>Unit price</th>
                          <th>Price</th>
                        </tr>
                      </thead>
                       <tbody>
                       {% for item in cart %}
                          {% with product=item.product %}
                            <tr>
                              <td>
                                      <a href="{{ product.get_absolute_url }}">
                                        <img width="100" height="100" src="{{ product.image.url}}">
                                      </a>
                              </td>
                              <td>{{ product.name }}</td>
                              <td>
                                  <form action="{% url 'cart:cart_add' product.id %}" method="post">
                                    {{ item.update_quantity_form.quantity }}
                                    {{ item.update_quantity_form.override }}
                                    <input type="submit" value="Update">
                                    {% csrf_token %}
                                  </form>
                              </td>
                                <td>
                                      <form action="{% url 'cart:cart_remove' product.id %}" method="post">
                                      <input type="submit" value="Remove">
                                      {% csrf_token %}
                                      </form>
                                </td>
                                <td class="num">${{ item.price }}</td>
                                <td class="num">${{ item.total_price }}</td>
                            </tr>
                            {% endwith %}
                        {% endfor %}
                       </tbody>

                    </table>
                    </div>
                    <hr class="mb-4" />
                    <div class="row">
                        <div class="col">
                            <a href="{% url 'shop:home' %}" class="btn btn-primary  btn-block">
                                Continue to shopping
                            </a>
                        </div>
                        <div class="col">
                            <a href="{% url 'orders:order_create' %}" class="btn btn-success  btn-block">
                                Continue to checkout
                            </a>
                        </div>

                    </div>

                    {% else %}
                        <h5 class="text-muted mb-4"> Your cart is empty. </h5>
                        <p>please add at least one product to the cart!</p>
                    {% endif %}
                  {% endwith %}

          </div>
        </div>
        <!--/.Card-->

      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-4 mb-4">
        <!-- Heading -->
        <h4 class="d-flex justify-content-between align-items-center mb-3">
          <span class="text-muted">Order Summary</span>
          {% with total_items=cart|length %}
          <span class="badge badge-secondary badge-pill">{{ total_items }}</span>
          {% endwith %}
        </h4>

        <p>
          Shipping and additional costs are calculated based on the values you have entered
        </p>
        
        <!-- Cart -->
        <ul class="list-group mb-3 z-depth-1">
          
          
            <li class="list-group-item d-flex justify-content-between">
              <span>Subtotal</span>
              <strong>${{ cart.get_total_price }}</strong>
            </li>

            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>{{ cart.coupon.code }} ({{ cart.coupon.discount }}% off)</small>
              </div>
              <span class="text-success">-${{ cart.get_discount|floatformat:2 }}</span>
            </li>

            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>${{ cart.get_total_price_after_discount|floatformat:2 }}</strong>
            </li>
          

        </ul>
        <!-- Cart -->
      
        <!-- Promo code -->
        <form class="card p-2" action="{% url 'coupons:apply' %}" method="post">
          <div class="input-group">
            {{ coupon_apply_form }}
            <div class="input-group-append">
              <button class="btn btn-secondary btn-md waves-effect m-0" type="button">
                Redeem
              </button>
            </div>
          </div>
          {% csrf_token %}
        </form>
        <!-- Promo code -->
      </div>
      <!--Grid column-->



      <!--Grid column-->
    </div>
    <!--Grid row-->
  </div>

{% endblock content %}